### PR TITLE
1.21.1

### PR DESCRIPTION
**Pull request by ModxVoldHunter**

### CODE REVIEW

**Comment by Lncvrt** [comment]
You didn't properly update gradle. The files will be mixed with 8.8 and 8.10 if they use this version.

**Comment by Lncvrt** [comment]
Properly updated in #54

**Comment by ModxVoldHunter** [comment]
oh damn, alright. ill close this

**Comment by Lncvrt** [comment]
> oh damn, alright. ill close this

all you do is 

```
./gradlew wrapper --gradle-version 8.10
```

and it will update it for you

**Comment by ModxVoldHunter** [comment]
oh that's gonna be helpful, anyways thank you!

**Pull request closed without merging**
